f = open("info.txt", "a")
f.write(input("Name: "))
f.write("\n")
f.write(input("Surname: "))
f.write("\n")
f.write(input("University name: "))
f.write("\n")
f.write(input("Field of study: "))
f.write("\n\n")
f.close()